# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: ./venv/bin/pytest
      language: system
      pass_filenames: false
      always_run: true
